# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cacheability}
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cyril Rohr"]
  s.date = %q{2010-01-05}
  s.description = %q{Transparent caching for your HTTP requests (heap, file, memcache). Cache invalidation on non-GET requests is supported. Built-in support for RestClient. Built upon Rack::Cache.}
  s.email = %q{cyril.rohr@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "cacheability.gemspec",
     "examples/grid5000.rb",
     "lib/cacheability.rb",
     "lib/cacheability/restclient.rb",
     "spec/cacheability_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/crohr/cacheability}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem that makes client-side caching of HTTP requests a no-brainer. Drop-in adapter for the rest-client gem with a single line: RestClient.enable(:caching) ! Supports heap, file and memcache storage, and cache invalidation on non-GET requests.}
  s.test_files = [
    "spec/cacheability_spec.rb",
     "spec/spec_helper.rb",
     "examples/grid5000.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack-cache>, [">= 0.5.0"])
    else
      s.add_dependency(%q<rack-cache>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<rack-cache>, [">= 0.5.0"])
  end
end

